apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-app
  name: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - image: nginx:1.25.1
        name: nginx
        resources:  
          requests:
            cpu: 100Mi
            memory: 0.5G
          limits:
            cpu: 150Mi
            memory: 0.75G
status: {}
